# Generated by Django 4.0 on 2022-03-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=65)),
                ('type', models.CharField(choices=[('temperatura', 'Temperatura'), ('umidade', 'Umidade'), ('pressao', 'Pressao'), ('vazao', 'Vazao'), ('bateria', 'Bateria')], default='pressao', max_length=20)),
                ('modelo', models.CharField(choices=[('Datalogger', 'Datalogger'), ('VRP', 'VRP')], default='Datalogger', max_length=20)),
                ('contrato', models.CharField(default='contrato', max_length=65)),
                ('endereco', models.CharField(default='Rua', max_length=100)),
                ('descricao', models.CharField(default='Datalogger v1.0', max_length=200)),
                ('intervalo_envio', models.IntegerField(default=15)),
                ('unidade_envio', models.CharField(default='min', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('format', models.CharField(blank=True, help_text='Deixe em branco para deixar no formato padrão (recomendado).', max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
    ]
