# Generated by Django 4.0.3 on 2022-03-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_alter_sensor_format_alter_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('umidade', 'Umidade'), ('pressao', 'Pressao'), ('vazao', 'Vazao'), ('bateria', 'Bateria')], default='pressao', max_length=20),
        ),
    ]
