# Generated by Django 4.0 on 2022-03-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_options_remove_recipe_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='teste', max_length=65, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
