# Generated by Django 4.0 on 2022-03-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_serial_number_recipe_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_steps',
            new_name='observations',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='servings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='servings_unit',
        ),
        migrations.AddField(
            model_name='recipe',
            name='contract',
            field=models.CharField(default='analisar', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='foto',
            field=models.ImageField(
                blank=True, default='', upload_to='recipes/fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_active',
            field=models.CharField(default='analisar', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='local_address',
            field=models.CharField(default='analisar', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='model_type',
            field=models.CharField(default='analisar', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Serial'),
        ),
    ]
