# Generated by Django 4.0 on 2022-03-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_preparation_steps_recipe_observations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cover',
        ),
    ]
